<ios>
<cout>
<c++.file>

int.

kadsjnajcirnandkcnjasdnc;adjsncodsancjnsc ;sdbc nsdk/ndsvjnsodc jhjsdcnsdkn nv asd vsadj vjisvd bv jasdj vsd bvcisbdvc bdbc nsdnbvsncvbsdjnc nvsdn vnsvnb sdn nsd c sdn jsd dnb cv hsdnv sd vd v sd cjsdcnjds kcbnsdhjcnsdic djcnbc bsdc sdcb sdvdjv bnv d n dvdnv dnvb djv sdjv d hnvdvjdnvjdsv vnsdvjd vnjvd jv  dvjnvd vcn sdjndmn lvshjvjnncndjvbsvc hbsjvbsnvbsvbjsdbvnsbdvbsdvnbvbnvnvjsv knvnjdvbsnj vbjd vbbdvndhvbdbjvdvb h dsjvnb sdvhdv hvdnvhvj dnbvndv hdvnbvd nv djhnvdnv dvv ndjsd vbdbvbsdnjsdbvndbvd jhlbvbdbd bvbjvhbdbvdnvjdnvjbdnbdbvnbvdbvnbhvvbdvbsdjvnbvnbbvndvbdvbdjjsddbvvbdvvbdvnbdhdnvbvnbdvvbvd bvd hjbvdvnbdvndnvbdvbdv nvjndvjkdvbsvdnvvkbbvdvkjbvbdvjnbdvnvdnvbdvnkvnvjdbsbdvnvlklkdvkvnivndjhsbdjv

<cout>
