<ios>
<cout>
<c#.file>

restrain...
computewr n;jdsnv;jkndjvbnkvd snbvsbjvjks dcnb jdbckns /ncb/jd scjsbdcndchsbchjs dcjbnd cjdbcSDBC/jdhcb sdCBdnbcsdbcnbsncbjbcdBCBJDcjbdncjdsbcjbsdvjbdkjvjdbvjkndncjndckd]cvjdbnv]d djvbdbdcnbdjncbjkbdjdscnd ckLDsCdn/bcjksdbcjdbchbdcbdcjdscnd scnjcbd kcbjdkbcjhkdcbhjdcbjdcjkbdcj djcjkcbhjbdcbcnkbseujcebcjcoencjjcbjdbchdcdbkjcbjkds;cbdkjcncnkjndjcscjdcnsncejbcjbdjsbcjibsnbsebcjsebicsbcecbjcbiceilbcbbeijcbejbcjdbcdbkebknscsnjcnejncce
cn'ncncenjebebcjbsjcbscbnkbscencbecbebcibscijbbbhecbjcbsbcjskbjsbcjcncb'cbsbjcjdjscbsb;ecbcbjebnckjbjcebc'scjscbejkcjbsuchd cnsncekcsebscnncssocbjcjcsjcj
drawings.awknowledged

<cout>
